name: Hourly Lego Amazon Deal Check (Watchlist)

on:
  schedule:
# Changed from 0 to 17 to bypass GitHub's top-of-the-hour traffic jam
    - cron: '19 */8 * * *'
  workflow_dispatch:
  
# Fixes the Node 20 deprecation warning globally
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  scrape:
    runs-on: macos-latest # <-- This is the magic bullet
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install curl_cffi beautifulsoup4

      - name: Run Amazon Scraper
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python Github_lego_Amazon_watchlist.py
