name: Hourly Lego Deal Check (Watchlist)

on:
  schedule:
# Changed from 0 to 17 to bypass GitHub's top-of-the-hour traffic jam
    - cron: '06 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Scraper (Watchlist)
        env:
          AMAZON_TAG: ${{ secrets.AMAZON_TAG }}
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }} # Add this line
        run: python Github_lego_watchlist.py
        
